// codegen.ts - Compile a behavior profile to a standalone TypeScript file
//
// V1 approach: embed the profile JSON and import the interpreter.
// The generated file can be used directly as a behavior module.

import type { BehaviorProfile } from './types';

/**
 * Generate a TypeScript source file from a behavior profile.
 * The generated file imports the interpreter and creates a BehaviorDefinition.
 */
export function generateProfileCode(profile: BehaviorProfile): string {
    const camelName = toCamelCase(profile.name);
    const profileJson = JSON.stringify(profile, null, 4);

    return `// Auto-generated behavior profile: ${profile.name}
// Generated at: ${new Date().toISOString()}
// Profile ID: ${profile.id}
//
// Do not edit this file directly. Use the Behavior Editor to modify the profile
// and re-compile.

import { createProfileBehavior } from '../../behavior-editor/interpreter';
import type { BehaviorProfile } from '../../behavior-editor/types';
import type { BehaviorDefinition } from '../bot-core/behavior-executor';

const PROFILE: BehaviorProfile = ${profileJson};

/**
 * ${profile.description || profile.name}
 *
 * States: ${profile.states.map(s => s.name).join(', ')}
 * Initial: ${profile.states.find(s => s.id === profile.initialStateId)?.name || 'none'}
 */
export function create${capitalize(camelName)}Behavior(
    getBehavior: (name: string, params?: Record<string, any>) => BehaviorDefinition | undefined
): BehaviorDefinition {
    return createProfileBehavior(PROFILE, getBehavior);
}

// Default export using a stub resolver (sub-behaviors must be registered at runtime)
export const ${camelName}Behavior = createProfileBehavior(PROFILE, () => undefined);
export default ${camelName}Behavior;
`;
}

function toCamelCase(str: string): string {
    return str
        .toLowerCase()
        .replace(/[^a-z0-9]+(.)/g, (_, c) => c.toUpperCase())
        .replace(/^[^a-z]/, '_$&');
}

function capitalize(str: string): string {
    return str.charAt(0).toUpperCase() + str.slice(1);
}
